# Generated by Django 3.2.8 on 2021-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=2048)),
                ('score', models.IntegerField()),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
